baseURL = "https://jnsn-b.github.io/radau-homepage/"
title = "Radau App"
theme = "PaperMod"
defaultContentLanguage = "de"
enableRobotsTXT = true
[pagination]
  pagerSize = 5

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1
    contentDir = "content/de"
    title = "Radau App"

[params]
  defaultTheme = "light"
  disableThemeToggle = true
  ShowReadingTime = false
  ShowShareButtons = false

  [params.homeInfoParams]
    Title = "Radau App"
    Content = "Die nachhaltige Musikbox für Kinder. Ohne Werbung. Ohne Cloud."
    
[params.assets]
  customCSS = ["css/extended/custom.css"]
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
